WEATHER_COLLECT_INTERVAL: int = 86400
WEATHER_BACKFILL_DAYS: int = 21
WEATHER_FETCH_TIMEOUT_SECONDS: int = 30
WEATHER_FETCH_MAX_RETRIES: int = 3
WEATHER_FETCH_RETRY_BACKOFF_SECONDS: list[int] = [5, 30, 120]
