POLL_INTERVAL_SECONDS: int = 3

CIRCUIT_BREAKER_FAILURE_THRESHOLD: int = 5
CIRCUIT_BREAKER_COOLDOWN_SECONDS: int = 60

RT_FETCH_TIMEOUT_SECONDS: int = 30
RT_FETCH_RETRY_ATTEMPTS: int = 2
RT_FETCH_RETRY_BACKOFF_SECONDS: list[int] = [1]

# Protobuf parsing
PB_MIN_PAYLOAD_BYTES: int = 10

# In-memory cache limits
CACHE_MAX_STOP_ID_TO_SEQ: int = 5000
